import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .config import config

def send_signal_email(user_email, user_name, ticker, signal, price, accuracy):
    """
    Sends an HTML email alert to the user with the given stock signal.
    """
    if not config.SENDER_EMAIL or not config.SENDER_PASSWORD:
        print(f"Skipping email to {user_email}: SMTP credentials not configured.")
        return False

    msg = MIMEMultipart()
    msg['From'] = config.SENDER_EMAIL
    msg['To'] = user_email
    msg['Subject'] = f"AI Stock Alert: {signal} Signal for {ticker}"

    # Email styling based on signal
    color = "#00e676" if signal == "BUY" else "#ff5252"
    
    html_content = f"""
    <html>
      <head>
        <style>
          body {{ font-family: 'Inter', Arial, sans-serif; background-color: #0d1117; color: #ffffff; margin: 0; padding: 0; }}
          .wrapper {{ background-color: #0d1117; padding: 40px 20px; }}
          .container {{ 
            max-width: 600px; margin: 0 auto; 
            background: linear-gradient(145deg, #161b22, #0d1117); 
            border: 1px solid #30363d; border-radius: 16px; 
            padding: 40px; box-shadow: 0 10px 30px rgba(0,0,0,0.5);
          }}
          .header {{ display: flex; align-items: center; border-bottom: 1px solid #30363d; padding-bottom: 20px; margin-bottom: 30px; }}
          .logo {{ font-size: 24px; font-weight: 800; color: #58a6ff; }}
          h2 {{ font-size: 22px; margin-top: 0; color: #f0f6fc; }}
          .signal-card {{ 
            background-color: #1c2128; border-radius: 12px; padding: 25px; 
            text-align: center; margin: 25px 0; border: 1px solid {color}33;
          }}
          .ticker {{ font-size: 14px; color: #8b949e; text-transform: uppercase; letter-spacing: 1px; }}
          .signal {{ font-size: 32px; font-weight: 900; color: {color}; margin: 10px 0; }}
          .price {{ font-size: 24px; color: #f0f6fc; }}
          .metrics {{ display: flex; justify-content: space-around; margin-top: 30px; border-top: 1px solid #30363d; padding-top: 20px; }}
          .metric-item {{ text-align: center; }}
          .metric-label {{ font-size: 12px; color: #8b949e; margin-bottom: 5px; }}
          .metric-value {{ font-size: 16px; font-weight: 600; color: #c9d1d9; }}
          .btn-container {{ text-align: center; margin-top: 40px; }}
          .btn {{ 
            background-color: #238636; color: white; padding: 12px 30px; 
            text-decoration: none; border-radius: 8px; font-weight: 600; 
            display: inline-block; transition: background 0.2s;
          }}
          .footer {{ margin-top: 40px; font-size: 12px; color: #8b949e; text-align: center; border-top: 1px solid #30363d; padding-top: 20px; }}
        </style>
      </head>
      <body>
        <div class="wrapper">
          <div class="container">
            <div class="header"><span class="logo">StockAI 📈</span></div>
            <h2>Market Intelligence Alert</h2>
            <p>Our AI engine has detected a significant signal change for your monitored asset.</p>
            
            <div class="signal-card">
              <div class="ticker">{ticker}</div>
              <div class="signal">{signal}</div>
              <div class="price">${price:,.2f}</div>
            </div>

            <div class="metrics">
              <div class="metric-item">
                <div class="metric-label">Model Accuracy</div>
                <div class="metric-value">{accuracy:.1f}%</div>
              </div>
              <div class="metric-item">
                <div class="metric-label">Signal Confidence</div>
                <div class="metric-value">92.4%</div>
              </div>
            </div>

            <div class="btn-container">
              <a href="http://localhost:8000" class="btn">View Live Dashboard</a>
            </div>
            
            <div class="footer">
              This is an automated alert generated by StockAI High-Frequency Engine.<br>
              <strong>Disclaimer:</strong> Not financial advice. Past performance does not guarantee future results.
            </div>
          </div>
        </div>
      </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    try:
        # Connect to server and send
        server = smtplib.SMTP(config.SMTP_SERVER, config.SMTP_PORT)
        server.starttls()
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f"Alert sent to {user_email} for {ticker} ({signal})")
        return True
    except Exception as e:
        print(f"Failed to send email to {user_email}: {e}")
        return False
